continent_mapping = {
    "ad": "Europe", "af": "Asia", "ai": "North America", "al": "Europe", "am": "Asia",
    "ao": "Africa", "aq": "Antarctica", "ar": "South America", "at": "Europe", "au": "Australia",
    "aw": "North America", "az": "Asia", "bb": "North America", "bd": "Asia", "be": "Europe",
    "bg": "Europe", "bh": "Asia", "bi": "Africa", "bj": "Africa", "bm": "North America",
    "bn": "Asia", "bo": "South America", "br": "South America", "bs": "North America", "bt": "Asia",
    "bw": "Africa", "by": "Europe", "bz": "North America", "ca": "North America", "ch": "Europe",
    "cl": "South America", "cm": "Africa", "cn": "Asia", "co": "South America", "cu": "North America",
    "cw": "North America", "cy": "Asia", "de": "Europe", "dj": "Africa",
    "dk": "Europe", "dm": "North America", "dz": "Africa", "ec": "South America", "ee": "Europe",
    "eg": "Africa", "er": "Africa", "es": "Europe", "et": "Africa", "fi": "Europe", "fj": "Oceania",
    "fm": "Oceania", "fr": "Europe", "ga": "Africa", "gd": "North America", "ge": "Asia",
    "gg": "Europe", "gh": "Africa", "gi": "Europe", "gl": "North America", "gm": "Africa",
    "gn": "Africa", "gp": "North America", "gr": "Europe", "gt": "North America", "gu": "Oceania",
    "gy": "South America", "hn": "North America", "hr": "Europe", "ht": "North America", "hu": "Europe",
    "id": "Asia", "ie": "Europe", "il": "Asia", "in": "Asia", "iq": "Asia", "ir": "Asia",
    "is": "Europe", "it": "Europe", "je": "Europe", "jm": "North America", "jo": "Asia",
    "jp": "Asia", "ke": "Africa", "kg": "Asia", "kh": "Asia", "ki": "Oceania", "km": "Africa",
    "kw": "Asia", "la": "Asia", "lb": "Asia", "li": "Europe", "lr": "Africa", "ls": "Africa",
    "lt": "Europe", "lu": "Europe", "lv": "Europe", "ly": "Africa", "ma": "Africa", "mc": "Europe",
    "md": "Europe", "mg": "Africa", "ml": "Africa", "mm": "Asia", "mn": "Asia", "mo": "Asia",
    "mq": "North America", "mr": "Africa", "ms": "North America", "mt": "Europe", "mu": "Africa",
    "mv": "Asia", "mw": "Africa", "mx": "North America", "my": "Asia", "mz": "Africa", "na": "Africa",
    "ne": "Africa", "ng": "Africa", "ni": "North America", "nl": "Europe", "no": "Europe",
    "np": "Asia", "nr": "Oceania", "nu": "Oceania", "om": "Asia", "pa": "North America", "pe": "South America",
    "ph": "Asia", "pk": "Asia", "pl": "Europe", "ps": "Asia", "pt": "Europe", "pw": "Oceania",
    "py": "South America", "qa": "Asia", "re": "Africa", "ro": "Europe", "rs": "Europe", "ru": "Europe",
    "rw": "Africa", "sc": "Africa", "sd": "Africa", "se": "Europe", "sg": "Asia", "si": "Europe",
    "sk": "Europe", "sn": "Africa", "so": "Africa", "sr": "South America", "sy": "Asia", "td": "Africa",
    "tg": "Africa", "th": "Asia", "tj": "Asia", "tk": "Oceania", "tn": "Africa", "to": "Oceania",
    "tr": "Asia", "tv": "Oceania", "tw": "Asia", "tz": "Africa", "ua": "Europe", "ug": "Africa",
    "uy": "South America", "uz": "Asia", "ve": "South America", "vn": "Asia", "vu": "Oceania",
    "ws": "Oceania", "xk": "Europe", "ye": "Asia", "yt": "Africa", "zm": "Africa", "zw": "Africa",
}